### ISSUE TITLE
We're clobbering the word "primary"

### ISSUE THREAD

**Issue by StommePoes** [Pearson-Higher-Ed/elements#147]
We have a rule
```
[class*="primary"]
```

This hits **absolutely everything** with this string of characters.

```
<div class="ng-primaryAction">First box of three</div>
```

Meaning we must do one of three things:

1. change this rule to ONLY affect Elements buttons meant to be primary buttons

OR

2. warn explicitly in our documentation that no consuming teams may ever have any classes containing this string

OR

3. Ensure consuming teams have explicit CSS to override the btn-primary styles.

**Comment by wyseguyonline** [comment]
We should write up a story to address this issue.  I'll talk to Joe.

**Comment by JasonLantz** [comment]
pr primaryFix addresses this issue....
