### ISSUE TITLE
elementsNoPlain isn't importing all the SASS files it should

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements#155]
Looks like the elementsNoPlain.scss file isn't importing all of the features of the elements SDK that is should be, specifically the following files are left out right now:

```
@import 'elements/responsive-utilities/responsive-utilities';
@import 'elements/icons/icons';
@import 'elements/buttons/buttons';
@import 'elements/grid/grid';
@import 'elements/templates/templates';
@import 'elements/presentation-strategies/presentation-strategies';
@import 'elements/inputs/inputs';
```

**Comment by parkerpearson** [comment]
Any updates on this or #166?

**Comment by StommePoes** [comment]
I had put them all in, so if they're not in now, someone took them out.

**Comment by parkerpearson** [comment]
Do you know what version that was?

**Comment by StommePoes** [comment]
I'm not sure the latest one but here's one where I was re-arranging stuff
https://github.com/Pearson-Higher-Ed/elements/commit/f1865580771e73a73fa2023729e225ee79534f11
and that's Feb 14th and somewhere before version 1.5.0

**Comment by StommePoes** [comment]
ah so they're in there, and at the base level I think this issue is closed..
