### ISSUE TITLE
Wrong weight of bold is being applied to UI Text

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements#158]
Bold UI text should use the 'semibold' weight, right now the `.pe-label--bold` class is bumping all the way up to bold. It looks like using `font-weight: 600` puts us at the right level.

**Comment by JasonLantz** [comment]
just issued a pr.... review in progress.

**Comment by JasonLantz** [comment]
change accepted...

**Comment by parkerpearson** [comment]
Yay! That was fast.
