### ISSUE TITLE
checkbox layout position off when label wraps

### ISSUE THREAD

**Issue by bobd9978** [Pearson-Higher-Ed/elements#167]
One of our forms (Create Account) has a checkbox with a label which is long enough to have to wrap. This is what we see with elements 1.4.2:
<img width="454" alt="not-wrapping" src="https://cloud.githubusercontent.com/assets/4248341/22904994/8b5caed2-f20c-11e6-962c-ecc62a0b788a.png">

Adding **display: inline-block** to the **input[type="checkbox"] ~ label** selector fixes it for me:
<img width="454" alt="wrapping" src="https://cloud.githubusercontent.com/assets/4248341/22905056/cc3716a4-f20c-11e6-9d7b-a12ba674ab49.png">

**Comment by StommePoes** [comment]
w00ts, fixed in #170   and merged

**Comment by bobd9978** [comment]
This is fixed. We're at 1.5.3 currently.

**Comment by JasonLantz** [comment]
bob says fixed... closing the issue
