### ISSUE TITLE
Inputs 'bounce' on focus/blur when applying pe-textLabelInput__label--label_focus class

### ISSUE THREAD

**Issue by bobd9978** [Pearson-Higher-Ed/elements#179]
We just started using the new pe-textLabelInput__label--label_focus class, setting it with this angular directive:
```
ng-class=
    "hasError('username') ? 'pe-textLabelInput__label--label_error' : 
    isFocused('username') ? 'pe-textLabelInput__label--label_focus' : 'pe-textLabelInput__label'"
```
Investigating, I found that the label element was switching between display: block and display: inline. There is currently this css selector:
```
.pe-textLabelInput__label {
  display: block;
}
```
I added the focus and error variants and it fixed it for me:
```
.pe-textLabelInput__label,
.pe-textLabelInput__label--label_focus,
.pe-textLabelInput__label--label_error {
  display: block;
}
```

**Comment by StommePoes** [comment]
This seems taken care of.
