### ISSUE TITLE
.pe-xs--visible class seems to be overridden to actually be hidden?

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements#192]
I'm trying to use the pe-{breakpoint}--hidden/visible classes, and it looks like the .pre-xs--visible one is actually hiding content rather than showing it at the xs viewport?

![screen shot 2017-04-17 at 1 40 17 pm](https://cloud.githubusercontent.com/assets/13319923/25101926/705e850e-2373-11e7-8325-e98ea9c0c725.png)

In this case the element has both the `.pe-xs--visible` and `.pe-sm--visible` classes.

**Comment by wyseguyonline** [comment]
https://github.com/Pearson-Higher-Ed/elements/pull/227
