### ISSUE TITLE
Bold UI Section headings use `<b>` tag

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements#193]
This is different than the method of bolding the UI Text, which uses a class, and also unnecessarily introduces another CSS element.

**Comment by StommePoes** [comment]
Wait, you want section headings bolded with a b tag?

**Comment by parkerpearson** [comment]
No, I'm pointing out that they are currently. At least that's how the demos
on the surge site work. Seems like they shouldn't be, but mostly I'd just
like the UI Headings to be consistent with the UI Text.

**Comment by StommePoes** [comment]
We should definitely not be using crap markup in our demos, because other teams will copy that garbage and it will spread like measles. I will find these.

**Comment by mhomolak** [comment]
Addressed in https://github.com/Pearson-Higher-Ed/elements/pull/194
