### ISSUE TITLE
Any thoughts on adding a webpack build

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/elements#201]
I would suggest `webpack` would be a better option than `gulp` since many teams uses webpack and it provides more control over the build.

Additionally, this would overcome the manual work of copying font and icons as well #200

**Comment by dinukadesilva** [comment]
Here is one reference on how fonts can be managed with the `webpack` build

https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/

**Comment by StommePoes** [comment]
Yup the gulp stuff kinda predates our current tech stack and indeed we have a story https://agile-jira.pearson.com/browse/DES-216

**Comment by mhomolak** [comment]
With this repo being deprecated and Elements-SDK using webpack I am closing this.
