### ISSUE TITLE
Shouldn't the textarea has similar styles as input

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/elements#234]
As seen below, the `border-radius` hasn't been added to textarea. Is this how it's expected. Just wondering :)

![image](https://user-images.githubusercontent.com/10680296/35377760-74866a88-01d6-11e8-841a-a4e8be4c229b.png)

![image](https://user-images.githubusercontent.com/10680296/35377801-94c30072-01d6-11e8-9be3-97591d6eae48.png)

**Comment by mhomolak** [comment]
Yes, this is the expected design.

For future questions similar to this please refer to http://uxframework.pearson.com/
