### ISSUE TITLE
Are default element styles optional?

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements#25]
In integrating the elements SDK into the design/docs site it appears the SDK adds default styles to all the built in tags like h1, h2, p, ul, etc.

Is there any way to turn that off so that the consumer manually specifies which elements take which styles through classes?

**Comment by parkerpearson** [comment]
For example, I've got a `div` which will end up containing some `p` tags generated by markdown. I want to apply the `.pe-label .pe-label--small` classes/styles to everything inside the div.

If I add those classes to the `div` directly then the default `p` styling provided in elements overrides the class styles because it's a more specific selector.

An alternative would be to use the sass `@extend` directive, unfortunately this doesn't work inside of media queries which I need in this case.

Unless I'm missing something it seems like the solution could be either 1) have a setting for turning off default styling or 2) provide `@include` mixins or just sass functions for each style so that elements can be targeted with more specificity in the css.

**Comment by StommePoes** [comment]
Okay we have http://jira.pearsoncmg.com/jira/browse/DES-151 (does not appear on the board).
